apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  namespace: default
data:
  CORE_URL: "http://{{ .Values.services.core.name }}:{{ .Values.services.core.port }}"
  CORE_DB_HOSTNAME: "mongo"
  CORE_DB_PORT: "27017"
  ML_URL: "http://{{ .Values.services.ml.name }}:{{ .Values.services.ml.port }}"
  REDIS_HOSTNAME: "{{ .Values.services.coreRedis.name }}"
  REDIS_PORT: "{{ .Values.services.coreRedis.port }}"
  REDIS_QUEUE: "{{ .Values.configMap.redisQueue }}"
  DEFAULT_USER_ID: "{{ .Values.configMap.defaultUserId }}"
  PUBLIC_VAPID: "{{ .Values.configMap.publicVapid }}"
