apiVersion: v1
kind: Secret
metadata:
  name: dark-secrets
  namespace: default
data:
  # Values need to be base 64 encoded
  MONGO_USERNAME: {{ .Values.secrets.mongoUser }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPw }}
  MONGO_INITDB_ROOT_USERNAME: {{ $.Values.secrets.mongoUser }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $.Values.secrets.mongoPw }}
  DOCKER_PASSWORD: {{ .Values.secrets.dockerPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry
type: Opaque
data:
  HTPASSWD: {{ $.Values.secrets.dockerRegistry }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $.Values.secrets.dockerConfig }}
---