{{- range $index, $service := .Values.services }}
{{ if $service.isClusterPublic }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ $service.name }}"
  name: "{{ $service.name }}"
spec:
  ports:
    - port: {{ $service.port }}
  type: ExternalName
  externalName: "{{ $service.name }}.develop.svc.cluster.local"
---
{{ end }}
{{ end }}
