services:
  web:
    image: "veryan4/web:${ENV}"
    build:
      context: ./
      dockerfile: ./web/Dockerfile
      args:
        - "ENVIRONMENT=${ENV}"

  core:
    image: "veryan4/core:${ENV}"
    build:
      context: ./
      dockerfile: ./core/Dockerfile

  scraper:
    image: "veryan4/scraper:${ENV}"
    build:
      context: ./
      dockerfile: ./scraper/Dockerfile

  ml:
    image: "veryan4/ml:${ENV}"
    build:
      context: ./
      dockerfile: ./ml/Dockerfile
