version: "3.7"

services:
  web:
    image: veryan4/web:develop
    build:
      context: ./
      dockerfile: ./web/Dockerfile
      args:
        - ENVIRONMENT=develop

  core:
    image: veryan4/core:develop
    build:
      context: ./
      dockerfile: ./core/Dockerfile

  scraper:
    image: veryan4/scraper:develop
    build:
      context: ./
      dockerfile: ./scraper/Dockerfile

  ml:
    image: veryan4/ml:develop
    build:
      context: ./
      dockerfile: ./ml/Dockerfile
