{{ range .Values.environments }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-restart
  namespace: {{ . }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["ml"]
    verbs:
      ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-restart
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ml-restart
subjects:
  - kind: ServiceAccount
    name: ml-restart
    namespace: {{ . }}
---
{{ end }}