{{ range .Values.environments }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dark-secrets
  namespace: {{ . }}
data:
  # Values need to be base 64 encoded
  JWT_SECRET: {{ $.Values.secrets.jwtSecret }}
  MONGO_USERNAME: {{ $.Values.secrets.mongoUser }}
  MONGO_PASSWORD: {{ $.Values.secrets.mongoPw }}
  GOOGLE_CLIENT_ID: {{ $.Values.secrets.googleClientId }}
  PRIVATE_VAPID: {{ $.Values.secrets.privateVapid }}
  MAIL_PASSWORD: {{ $.Values.secrets.mailPassword }}
  AIRTABLE_API_KEY: {{ $.Values.secrets.airtableApiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: {{ . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $.Values.secrets.dockerConfig }}
---
{{ end }}