{{ range $ind, $env := .Values.environments }}
{{ range $index, $service := $.Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $service.name }}
  name: {{ $service.name }}
  namespace: {{ $env }}
spec:
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
  selector:
    app: {{ $service.name }}
---
{{ end }}
{{ end }}