{{ range .Values.environments }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-restart
  namespace: {{ . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-registry
  namespace: {{ . }}
imagePullSecrets:
- name: docker-registry
---
{{ end }}