apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solr-exporter
  name: solr-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: solr-exporter
  template:
    metadata:
      labels:
        app: solr-exporter
    spec:
      containers:
        - name: solr-exporter
          image: veryan4/solr
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: core-env
            - name: SOLR_HOSTNAME
              value: solr-exporter
            - name: SOLR_PORT
              value: "9854"
          args:
            - "/opt/solr-8.4.1/contrib/prometheus-exporter/bin/solr-exporter"
            - "-p"
            - "9854"
            - "-b"
            - "http://core-solr:8983/solr"
            - "-f"
            - "/opt/solr-8.4.1/contrib/prometheus-exporter/conf/solr-exporter-config.xml"
            - "-n"
            - "8"
          ports:
            - containerPort: 9854
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: solr-exporter
spec:
  ports:
    - port: 9854
      targetPort: 9854
  selector:
    app: solr-exporter
status:
  loadBalancer: {}
