replicaCount: 1

environments:
  - "develop"
  - "production"

domainName: truba.news

registry: veryan4

configMap:
  redisQueue: "controller"
  defaultUserId: "1a9c14f8-6610-4793-89b3-128f78d2b720"
  publicVapid: "BAQE9ZzSk_rjUO3q-7jpmI_ml4C_EFefijwFfJSlwpqqXB01PaPOYorJJmVlN7WrbseedqMoy-6ZWSSZJQlECWE"
  airtableId: "appXAWgdvcKQpJKiz"
  mailSenderEmail: "info@truba.news"
  mailSenderName: "truba news"

#DO NOT COMMIT CHANGES TO SECRET VALUES TO GIT
secrets:
  jwtSecret: foobar
  mongoUser: foobar
  mongoPw: foobar
  googleClientId: foobar
  privateVapid: foobar
  dockerConfig: foobar
  mailPassword: foobar
  airtableApiKey: foobar

schedules:
  mlRestart: "0 8 * * *"
  training: "0 7 * * 0-6"
  scraper:
    en: "0 * * * *"
    fr: "30 * * * *"
  push: "0 9 * * 0-6"

services:
  core:
    name: core
    imageName: core
    isCustomImage: true
    isClusterPublic: true
    port: 5057
    command:
      - /app/core
    env:
      coreUrl:
        name: CORE_URL
      dbHostName:
        name: CORE_DB_HOSTNAME
      dbPort:
        name: CORE_DB_PORT
      mongoUsername:
        name: MONGO_USERNAME
        isSecret: true
      mongoPassword:
        name: MONGO_PASSWORD
        isSecret: true
      redisHostname:
        name: REDIS_HOSTNAME
      redisPort:
        name: REDIS_PORT
      redisQueue:
        name: REDIS_QUEUE
      mlUrl:
        name: ML_URL
      airtableApiKey:
        name: AIRTABLE_API_KEY
        isSecret: true
      airtableId:
        name: AIRTABLE_ID

  coreUi:
    name: coreui
    imageName: core
    isCustomImage: true
    hasIngress: true
    port: 6168
    command:
      - /app/coreui
    env:
      coreUiPort:
        name: CORE_UI_PORT
      dbHostName:
        name: CORE_DB_HOSTNAME
      dbPort:
        name: CORE_DB_PORT
      mongoUsername:
        name: MONGO_USERNAME
        isSecret: true
      mongoPassword:
        name: MONGO_PASSWORD
        isSecret: true
      redisHostname:
        name: REDIS_HOSTNAME
      redisPort:
        name: REDIS_PORT
      redisQueue:
        name: REDIS_QUEUE
      mlUrl:
        name: ML_URL
      jwtSecret:
        name: JWT_SECRET
        isSecret: true
      googleClientId:
        name: GOOGLE_CLIENT_ID
        isSecret: true
      defaultUser:
        name: DEFAULT_USER_ID
      privateVapid:
        name: PRIVATE_VAPID
        isSecret: true
      publicVapid:
        name: PUBLIC_VAPID
      appUrl:
        name: APP_URL
      appWWWUrl:
        name: APP_WWW_URL
      mailAddress:
        name: MAIL_ADDRESS
      mailSenderName:
        name: MAIL_SENDER_NAME
      mailPassword:
        name: MAIL_PASSWORD
        isSecret: true
      airtableApiKey:
        name: AIRTABLE_API_KEY
        isSecret: true
      airtableId:
        name: AIRTABLE_ID

  coreWorker:
    name: worker
    imageName: core
    isCustomImage: true
    port: 6168
    command:
      - /app/worker
    env:
      dbHostName:
        name: CORE_DB_HOSTNAME
      dbPort:
        name: CORE_DB_PORT
      mongoUsername:
        name: MONGO_USERNAME
        isSecret: true
      mongoPassword:
        name: MONGO_PASSWORD
        isSecret: true
      redisHostname:
        name: REDIS_HOSTNAME
      redisPort:
        name: REDIS_PORT
      redisQueue:
        name: REDIS_QUEUE
      mlUrl:
        name: ML_URL
      airtableApiKey:
        name: AIRTABLE_API_KEY
        isSecret: true
      airtableId:
        name: AIRTABLE_ID

  coreMcp:
    name: mcp
    imageName: core
    isCustomImage: true
    port: 8000
    command:
      - /app/mcp
    env:
      dbHostName:
        name: CORE_DB_HOSTNAME
      dbPort:
        name: CORE_DB_PORT
      mongoUsername:
        name: MONGO_USERNAME
        isSecret: true
      mongoPassword:
        name: MONGO_PASSWORD
        isSecret: true
      redisHostname:
        name: REDIS_HOSTNAME
      redisPort:
        name: REDIS_PORT
      redisQueue:
        name: REDIS_QUEUE


  coreRedis:
    name: redis
    imageName: redis:7.2-alpine
    isClusterPublic: true
    port: 6379
    env:
      redisHostname:
        name: REDIS_HOSTNAME
      redisPort:
        name: REDIS_PORT
      redisQueue:
        name: REDIS_QUEUE

  web:
    name: "web"
    port: 80
    imageName: web
    hasIngress: true
    isCustomImage: true
    env:
      nginxHost:
        name: NGINX_HOST
      nginxPort:
        name: NGINX_PORT

  ml:
    name: ml
    port: 5158
    imageName: ml
    isCustomImage: true
    isClusterPublic: true
    command:
      - gunicorn
      - --workers=2
      - --worker-class=uvicorn.workers.UvicornH11Worker
      - --bind=0.0.0.0:5158
      - --timeout=1200
      - controller:app
    volume:
      name: models
      path: /tf_models
      storage: 10Gi
    env:
      dbHostname:
        name: CORE_DB_HOSTNAME
      dbPort:
        name: CORE_DB_PORT
      mongoUsername:
        name: MONGO_USERNAME
        isSecret: true
      mongoPW:
        name: MONGO_PASSWORD
        isSecret: true
      coreUrl:
        name: CORE_URL
